- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.7.1  # Use the ref you want to point at
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=250']
  - id: trailing-whitespace
  - id: end-of-file-fixer