# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
title:              "thingelstad.com"
description:        "Personal website of Jamie Thingelstad"

author:             Jamie Thingelstad

social:
  twitter:          thingles
  github:           thingles
  linkedin:         jthingelstad
  email:            jamie@thingelstad.com
  microblog:        jthingelstad
  pinboard:         thingles

# URL
url:                "http://thingelstad.com" # the base hostname & protocol for your site
#url:                "http://localhost:4000" # use this url when develop
baseurl:            "" # the subpath of your site, e.g. /blog

# Affiliates
affiliate:
  amazon:           "thingelstad01-20"
  itunes:           "1001lxyE"


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           America/Chicago
permalink:          /:year/:title/

# Pagination
paginate:           10
paginate_path:      /page:num/

# Feed config
feed_posts:         20

# Analytics
google_analytics:   UA-49944629-1

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - icon:           "<i class='fa fa-user' aria-hidden='true' title='About'></i>"
    name:           "About"
    url:            "/about/"
  - icon:           "<i class='fa fa-camera' aria-hidden='true' title='Photos'></i>"
    name:           "Photos"
    url:            "/photos/"
  - icon:           "<i class='fa fa-flask' aria-hidden='true' title='Projects'></i>"
    name:           "Projects"
    url:            "/projects/"
  - icon:           "<i class='fa fa-thumb-tack' aria-hidden='true' title='Links'></i>"
    name:           "Links"
    url:            "/links/"
  - icon:           "<i class='fa fa-envelope' aria-hidden='true' title='Weekly Thing'></i>"
    name:           "Weekly Thing"
    url:            "/weekly-thing/"
  - icon:           "<i class='fa fa-tags' aria-hidden='true' title='Tags'></i>"
    name:           "Tags"
    url:            "/tags/"
  - icon:           "<i class='fa fa-archive' aria-hidden='true' title='Archive'></i>"
    name:           "Archive"
    url:            "/archive/"
  - icon:           "<i class='fa fa-comment' aria-hidden='true' title='Microblog'></i>"
    name:           "Microblog"
    url:            "http://micro.thingelstad.com/"    

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:            [vendor]
