# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "thingelstad.com"

author:
  name:             Jamie Thingelstad
  twitter:          thingles
  github:           thingles
  linkedin:         jthingelstad
  email:            jamie@thingelstad.com

# URL
url:                "http://thingelstad.com" # the base hostname & protocol for your site
#url:                "http://localhost:4000" # use this url when develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           America/Chicago
permalink:          /:year/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about/"
  - name:           "Photos"
    url:            "/photos/"
  - name:           "Archive"
    url:            "/archive/"
  - name:           "Tags"
    url:            "/tags/"
  - name:           "Now"
    url:            "/now/"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
