# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
title:              "thingelstad.com"
description:        "Personal website of Jamie Thingelstad"

author:             Jamie Thingelstad

social:
  twitter:          thingles
  github:           thingles
  linkedin:         jthingelstad
  email:            jamie@thingelstad.com
  microblog:        jthingelstad
  pinboard:         thingles

# URL
url:                "http://thingelstad.com" # the base hostname & protocol for your site
#url:                "http://localhost:4000" # use this url when develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           America/Chicago
permalink:          /:year/:title/

# Pagination
paginate:           10
paginate_path:      /page:num/

# Feed config
feed_posts:         20

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about/"
  - name:           "Photos"
    url:            "/photos/"
  - name:           "<i class='fa fa-archive' aria-hidden='true'></i>"
    url:            "/archive/"
  - name:           "<i class='fa fa-tags' aria-hidden='true'></i>"
    url:            "/tags/"
  - name:           "<i class='fa fa-bookmark' aria-hidden='true'></i>"
    url:            "/links/"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
