---
upload_path: "/assets/posts/:year:"
frontmatter_file_url_template: "/assets/posts/:year:"
body_file_url_template: "/assets/posts/:year:"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections: 
