---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
upload_dir: assets/posts
public_path: "/assets/posts"
front_matter_path: "/assets/posts"
use_front_matter_path: false
file_template: ":year:/:filename:"
