backend:
  name: github
  repo: thingles/thingles.github.io # Path to your Github repository
  branch: master # Branch to update
media_folder: "assets" # Media files will be stored in the repo under images/uploads 